Backend_FTT.py

The recent ordering of files had broken this module. We should have unit tests to prevent this..

Fixed backend.py

---

docs/Update manuals/FTT-Power update manual.md

remove the statement to update MEWW. It is already done endogenously.

Update FTT-Power update manual.md

---

Backend_FTT.py

.append has been deprecated in pandas 2.0, so it has been changed to pd.concat

.append update

---

docs/Update manuals/FTT-Transport update manual.md

This is a first draft of the FTT-Transport update manual.

FTT-Transport update manual

---

SourceCode/Power/ftt_p_costc.py
SourceCode/Power/ftt_p_main.py
settings.ini

Zoé, I have cleaned up the code a bit. Let me know if it's now sufficiently clear?

Clean up cost-curves code after question

---

Utilities/titles/VariableListing.csv

New master files added

---

Utilities/titles/VariableListing.csv

So that they can be summed in front end. Closes #100.

Remove /y from units

---

SourceCode/Transport/ftt_tr_main.py

Regulation in transport now in capacity space. This has been corrected in the code and also clarified in the spreadsheets.
Tested against Fortran model.

Correction to FTT-Tr regulation

---

SourceCode/support/input_functions.py
settings.ini

Rewrite input_functions so it has 3 fewer branches. Also ensures warnings for missing variables in VariableListing are only printed once.

Refactor input_functions.py

---

SourceCode/Power/ftt_p_lcoe.py

Bring over some changes from the cascading_tipping_point branch that may help finding differences with FORTRAN.

Tidy up ftt_p_lcoe

---

SourceCode/support/debug_messages.py
SourceCode/support/input_functions.py

included reg_index for region loop

more detailed error messages

---

SourceCode/Steel/ftt_s_main.py

Merge test

---

SourceCode/Steel/ftt_s_rawmaterials.py

Added file on the raw materials code: converted directly from Fortran to Python

Steel arpan

---

SourceCode/Steel/ftt_s_rawmaterials.py

Direct conversion from Fortran to Python

adding the full raw materials code

---

SourceCode/Steel/ftt_s_main.py
SourceCode/Steel/ftt_s_rawmaterials.py

Femke added a couple of lines of code. The baseline ran using the run file. Merging to main FTT-Steel branch.

running the rawmaterials code

---

SourceCode/Steel/ftt_s_main.py

Based on the new ftt_core code. Called the new get_Sales function and activated the learning by doing section in the main file. Ran it through the run file. No errors. Baseline runs successfuly.

Learning by doing for steel

---

SourceCode/Steel/ftt_s_main.py

With minor changes to the main file as well as added a short checklist of things to add in specific sections of the code.

Compared with fortran and rearranged code

---

SourceCode/Steel/ftt_s_fuel_consumption.py

Femke solved the error with sjef in the fuel consumption code and now the baseline runs.

Fuel consumption file errors solved

---

SourceCode/Steel/ftt_s_main.py

Added a to-do list of remaining items to cover

Minor changes to the main file

---

SourceCode/Steel/ftt_s_main.py

Added the learning by doing codes in the ftt_s_main file. Put all the LBD codes together. Converted the code directly from Fortran. Lines b/w 800 to 905 leaving out the E3ME related parts.

Steel arpan 12 jun

---

SourceCode/Freight/ftt_fr_main.py
SourceCode/Power/ftt_p_main.py
SourceCode/initialise_csv_files.py
SourceCode/support/convert_masterfiles_to_csv.py

This seeks to automatically update the csv files when the masterfiles is newer than the newest csv files. I think this will make it easier to update the model / switch between branches with different data. Should we try do finish this at the summer school?
Doesn't quite work yet, but nearly done:
* It seems to update all csv files when one masterfile is updated
* It's asking for confirmation to overwrite gamma values even when not

Update csv when masterfiles updated

---

SourceCode/Transport/ftt_tr_lcot.py
SourceCode/Transport/ftt_tr_main.py
SourceCode/Transport/ftt_tr_survival.py
Utilities/titles/VariableListing.csv

Some of the country groupings for FTT-Tr costs were wrong. This update fixes this and corrects when learning starts in order to be consistent with the Fortran model. 
This pull request also contains a fix to how the fuel tax in FTT-Tr is implemented.

Correcting FTT-Tr costs

---

SourceCode/Transport/ftt_tr_main.py

Emissions in FTT-Tr were zero from 2020 onward. The cause was emis_corr going to zero.

Transport emissions correction fix

---

SourceCode/Freight/ftt_fr_main.py
SourceCode/Industrial_Heat/ftt_chi_main.py
SourceCode/Industrial_Heat/ftt_fbt_main.py
SourceCode/Industrial_Heat/ftt_mtm_main.py
SourceCode/Industrial_Heat/ftt_nmm_main.py
SourceCode/Industrial_Heat/ftt_ois_main.py
SourceCode/Power/ftt_p_costc.py
SourceCode/Power/ftt_p_surv.py
SourceCode/Transport/ftt_tr_main.py
SourceCode/support/cross_section.py

Gives a 10% speed boost on these lines (less than I initially thought). Cleaner, so still the preferred option. 
Rishi, can you double check the output is the same in the two versions. I've checked for power, but not consistently. I've not checked for the other models. The freight model does not work in either version, so ignore that for now. 
Closes #182

Replace deepcopy with copy

---

SourceCode/Freight/ftt_fr_main.py
SourceCode/Heat/ftt_h_main.py
SourceCode/Power/ftt_p_main.py
SourceCode/Transport/ftt_tr_main.py
settings.ini

This will go back to E3ME, was overestimated before.

Fix investment cost estimates

---

SourceCode/Power/ftt_p_main.py

Clean up extra storage demand
